---
name: image-build
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  OPENWRT_VERSION: 25.12.2
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - image: ath79-nand
            profile: glinet_gl-ar750s-nor-nand
            packages: luci ip-tiny ip-bridge nano tcpdump -dnsmasq dnsmasq-full luci-app-travelmate
              luci-app-pbr luci-proto-wireguard wireguard-tools
          - image: ramips-mt7621
            profile: netgear_r6220
            packages: luci ip-tiny ip-bridge nano tcpdump -wpad-basic-wolfssl -wpad-basic-mbedtls
              wpad-mesh-wolfssl wget iwinfo ebtables
          - image: ramips-mt7621
            profile: mikrotik_routerboard-750gr3
            packages: luci ip-tiny ip-bridge nano tcpdump luci-app-ddns luci-mod-rpc
              ca-certificates luci-app-sqm luci-proto-wireguard
              avahi-daemon -dnsmasq dnsmasq-full
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # - name: install dependencies
      #   run: sudo ./install_dependencies.sh
      # - name: build image
      #   run: ./build.sh
      - uses: izer-xyz/openwrt-imagebuilder-action@v6
        with:
          image: ${{ matrix.image }}
          profile: ${{ matrix.profile }}
          openwrt-version: ${{ env.OPENWRT_VERSION }}
          packages: ${{ matrix.packages }}

      # - name: list build files
      #   run: ls -lh ./bin
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.profile }}-binaries
          path: ./bin/*.bin
  # upload to github release
  release:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: get artifacts
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          name: release-${{ env.OPENWRT_VERSION }}-${{ steps.date.outputs.date }}
          artifacts: '*.bin'
          tag: release-${{ env.OPENWRT_VERSION }}-${{ steps.date.outputs.date }}
          commit: main
