name: image-build
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: ./install_dependencies.sh
      - name: build image
        run: ./build_image.sh
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ar750s-sysupgrade.bin
          path: ./ar750s-sysupgrade.bin
  # upload to github release
  release:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: get  image
        uses: actions/download-artifact@v4.1.8
        with:
          name: ar750s-sysupgrade.bin
      # - name: create release
      #   uses: ncipollo/release-action@v1.15.0
      #   with:
      #     name: release-${{ steps.date.outputs.date }}
      #     artifacts: ar750s-sysupgrade.bin
      #     tag: release-${{ steps.date.outputs.date }}
      #     commit: main
